### ISSUE TITLE
HSTS error for www on Firefox

### ISSUE THREAD

**Issue by funnelfiasco** [KYOSS/website#58]
Trying to visit www.kyoss.dev on Firefox gives an HSTS error (Chrome apparently doesn't care):

```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.kyoss.dev. The certificate is only valid for the following names: *.github.io, github.io, githubusercontent.com, www.github.com, *.github.com, *.githubusercontent.com, github.com
```

(going to kyoss.dev works as expected)

This may be because www.kyoss.dev is a CNAME for kyoss.dev instead of for kyoss.github.io, as suggested in the [GitHub docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant). 

The [Meetup page](https://www.meetup.com/louisvilleopensourceprogramming/events/302443232/) lists `www.kyoss.dev`, which is how I ended up discovering this issue.

**Comment by jsquyres** [comment]
@InfoSec812 It looks like the certificate only has the name `kyoss.dev`, not `www.kyoss.dev`.  If I'm reading https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site?platform=linux#configuring-a-subdomain, we should have the www.kyoss.dev CNAME pointing to kyoss.github.io, not kyoss.dev.

It looks like our namecheap kyoss.dev domain has custom DNS servers at comodo, and I don't think I have access to those.

If you read those github docs and agree with my assessment, could you update our CNAME?  We might need to remove / re-add the github custom domain to make it re-provision the TLS certificate to include both kyoss.dev and www.kyoss.dev.

**Comment by InfoSec812** [comment]
I have updated the DNS records. @funnelfiasco - Let us know if this resolves your issue. I cannot reproduce this is Firefox on Linux.

**Comment by jsquyres** [comment]
https://www.kyoss.dev now appears to work for me correctly in Chrome and Firefox (it failed for me in both before @InfoSec812's DNS changes).

Thanks for the heads-up!

**Comment by funnelfiasco** [comment]
Late to the party, but I agree this is fixed. Thanks!
